	all_obj = CreateObject(8947, -640.653442, 1246.014038, 8.472473, -0.000003, 0.000029, -7.800059, 200.0); // 2
	SetObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	SetObjectMaterial(all_obj, 2, 16136, "des_telescopestuff", "stoneclad1", 0);
	all_obj = CreateObject(13701, -648.453369, 1282.710815, 2.898101, 0.000007, 0.000000, 89.999977, 200.0); // 3
	SetObjectMaterial(all_obj, 0, 6988, "vgnfremnt1", "casinopillar1_256", 0);
	SetObjectMaterial(all_obj, 1, 13816, "lahills_safe1", "gry_roof", 0);
	SetObjectMaterial(all_obj, 4, 6522, "cuntclub_law2", "marinawindow1_256", 0);
	all_obj = CreateObject(8947, -709.026733, 1333.316772, 6.607512, 0.000000, 0.000000, 177.100006, 200.0); // 2
	SetObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	SetObjectMaterial(all_obj, 2, 3603, "bevmans01_la", "sjmlahus29", 0);
	CreateObject(3639, -749.743103, 1337.342896, 17.467499, 0.000000, 0.000000, -12.899992, 200.0); // 0
	all_obj = CreateObject(8947, -777.783630, 1337.345337, 9.927519, 0.000000, 0.000000, 257.100006, 200.0); // 2
	SetObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	SetObjectMaterial(all_obj, 2, 7088, "casinoshops1", "fakestone1_LA", 0);
	all_obj = CreateObject(8947, -746.307861, 1286.581421, 10.852507, 0.000003, 0.000006, 32.200073, 200.0); // 2
	SetObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	SetObjectMaterial(all_obj, 2, 14387, "dr_gsnew", "mp_stonefloor", 0);
	all_obj = CreateObject(8947, -728.205994, 1258.622559, 9.772521, 0.000004, 0.000004, 48.599976, 200.0); // 2
	SetObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	SetObjectMaterial(all_obj, 2, 3603, "bevmans01_la", "sjmlahus29", 0);
	all_obj = CreateObject(13695, -686.631836, 1246.416016, 10.393309, -0.000014, -0.000001, -7.499960, 200.0); // 2
	SetObjectMaterial(all_obj, 0, 18202, "w_towncs_t", "hatwall256hi", 0);
	SetObjectMaterial(all_obj, 6, 7088, "casinoshops1", "fakestone1_LA", 0);
	all_obj = CreateDynamicObject(11559, -648.765991, 1299.390015, -2.935302, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 600.0); // 4
	SetDynamicObjectMaterial(all_obj, 3, 12866, "ce_ground07", "desgrassbrn", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(11535, -806.507996, 1310.530029, 7.228758, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 600.0); // 2
	SetDynamicObjectMaterial(all_obj, 4, 12866, "ce_ground07", "desgrassbrn", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	CreateDynamicObject(762, -611.133057, 1218.801514, 9.951721, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(715, -621.390564, 1221.938721, 19.307068, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(800, -619.391296, 1231.418457, 10.693115, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(983, -621.729919, 1242.800049, 12.302673, -0.000003, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 18368, "cs_mountaintop", "des_woodrails", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(983, -620.946533, 1248.555420, 12.302673, -0.000003, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 18368, "cs_mountaintop", "des_woodrails", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(983, -625.288452, 1240.108276, 12.302673, -0.000003, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 18368, "cs_mountaintop", "des_woodrails", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(823, -631.673889, 1228.632324, 11.262114, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(826, -619.460022, 1253.417480, 3.346405, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(983, -623.651855, 1252.128174, 12.302673, -0.000003, 0.000029, 442.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 18368, "cs_mountaintop", "des_woodrails", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(669, -632.148499, 1234.879395, 10.882353, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(618, -620.087585, 1257.990601, 2.246428, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -635.458130, 1233.419312, 12.214874, 180.000000, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -635.177002, 1235.401367, 12.009886, 89.999992, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(11496, -612.871033, 1270.003662, 0.459410, 0.000029, 0.000000, 89.999908, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(13754, -630.793762, 1246.614380, 9.757904, -0.000003, 0.000029, 82.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 7, 3998, "civic04_lan", "twintWall1_LAn", 0);
	all_obj = CreateDynamicObject(18762, -634.498108, 1240.356323, 12.009886, 89.999992, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(11496, -612.866028, 1272.054932, 0.454405, -0.000029, 0.000000, -89.999908, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1499, -637.435913, 1233.681396, 11.514678, -0.000003, 0.000029, 352.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(1232, -637.915161, 1233.755127, 12.414886, 360.000000, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -637.915161, 1233.755127, 12.214874, 180.000000, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	//all_obj = CreateDynamicObject(975, -642.783447, 1234.442993, 13.034088, 0.000000, 0.000000, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	all_obj = CreateDynamicObject(18762, -632.250916, 1256.757446, 12.214874, 180.000000, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(11496, -616.321716, 1282.537964, 0.454405, -0.000022, -0.000029, -179.999725, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1232, -647.664490, 1235.089600, 12.414886, 360.000000, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -647.664490, 1235.089600, 12.214874, 180.000000, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(11496, -618.372986, 1282.542847, 0.459410, 0.000022, 0.000029, -0.000037, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -638.556702, 1257.701172, 13.125029, 0.000001, 0.000030, 82.199913, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(17071, -635.442810, 1260.096924, 2.314940, 0.000000, 0.000000, 110.700043, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 16175, "des2vegas_join", "des_rocky1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 16103, "des_ne", "des_yelrock", 0);
	CreateDynamicObject(9321, -642.069214, 1254.228638, 12.926025, -0.000003, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(11496, -612.871033, 1293.025391, 0.459410, 0.000022, 0.000000, 89.999931, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -650.601807, 1235.495605, 12.009886, 89.999992, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(691, -636.261719, 1262.955078, 3.614959, 0.000000, 0.000000, 20.699999, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(11496, -612.866028, 1295.076660, 0.454405, -0.000022, 0.000000, -89.999931, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -651.785461, 1235.655518, 12.004881, 89.999992, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(886, -653.323120, 1231.547607, 11.037291, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -653.857605, 1235.918701, 13.125029, -0.000003, 0.000022, -97.800087, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(800, -633.333801, 1271.975464, 2.568846, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(895, -652.536377, 1239.438477, 11.241119, 0.000000, 0.000000, 45.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18980, -644.132202, 1258.404175, 12.009886, 89.999992, 0.000029, 82.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(803, -655.558044, 1232.388916, 11.902098, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(819, -653.239868, 1240.007446, 10.851135, 0.000000, 0.000000, 45.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -656.729248, 1236.333862, 12.004881, 89.999992, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -657.018372, 1236.351074, 13.125029, -0.000003, 0.000022, -97.800087, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(3084, -656.072388, 1238.216797, 11.459013, 270.000000, 180.000031, -7.800059, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(3084, -655.635498, 1241.406006, 11.459013, 270.000000, 180.000031, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(782, -659.353149, 1232.268311, 11.117308, 0.000000, 0.000000, -90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18980, -648.570618, 1259.006470, 12.004881, 89.999992, 0.000029, 82.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(736, -648.908325, 1261.575195, 16.834930, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(819, -657.217712, 1240.162231, 10.851135, 0.000000, 0.000000, -97.200043, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19543, -639.053589, 1258.205566, -19.726929, 89.999992, 90.000000, -97.800056, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 12866, "ce_ground07", "desgrassbrn", 0);
	CreateDynamicObject(779, -658.176636, 1240.520630, 11.471130, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(812, -661.885193, 1232.924561, 13.423979, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(3934, -654.599304, 1250.897583, 11.516020, -0.000003, 0.000029, 82.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(8947, -655.256531, 1248.014404, 8.472473, -0.000003, 0.000029, -7.800059, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 7555, "bballcpark1", "ws_carparknew2", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(984, -651.189026, 1259.432373, 13.125029, 0.000001, 0.000030, 82.199913, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(1255, -645.654602, 1268.724609, 8.753143, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(11496, -616.321716, 1305.571411, 0.454405, -0.000022, -0.000022, -179.999771, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -661.673157, 1237.011597, 12.004881, 89.999992, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1281, -640.794922, 1278.635010, 9.023132, 0.000000, 0.000000, 100.400002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(1255, -645.902039, 1270.372803, 8.753143, 0.000000, 0.000000, 11.199999, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(11496, -618.372986, 1305.576294, 0.459410, 0.000022, 0.000022, -0.000037, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -663.625488, 1237.275146, 12.214874, 180.000000, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -654.349365, 1259.863281, 13.125029, 0.000001, 0.000030, 82.199913, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -663.382996, 1239.264771, 12.009886, 89.999992, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -662.766602, 1243.348877, 13.125029, 0.000003, 0.000023, 172.199875, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -662.900879, 1242.821289, 12.004881, 89.999992, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(11496, -612.871033, 1316.058838, 0.459410, 0.000014, 0.000000, 89.999954, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -662.223450, 1247.765137, 12.004881, 89.999992, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1281, -649.522339, 1272.983276, 9.023132, 0.000000, 0.000000, 27.499998, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -661.545776, 1252.709473, 12.004881, 89.999992, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(11496, -612.866028, 1318.110107, 0.454405, -0.000014, 0.000000, -89.999954, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -661.248779, 1254.433716, 13.125029, 0.000003, 0.000023, 172.199875, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -660.866821, 1257.663940, 12.004881, 89.999992, 0.000029, 172.199936, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(820, -669.003174, 1238.717163, 10.051910, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -660.427917, 1260.616699, 12.214874, 180.000000, 0.000029, 262.199951, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(800, -666.371948, 1246.289307, 10.434204, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(8615, -654.044373, 1274.306885, 10.433135, 0.000000, 0.000000, 90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(672, -672.185852, 1235.553223, 12.212248, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(715, -667.395752, 1252.290649, 16.273438, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19543, -653.429321, 1260.175903, -19.726929, 89.999992, 90.000000, -97.800056, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(13701, -648.433350, 1282.700806, -4.741911, 0.000007, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(all_obj, 4, 6522, "cuntclub_law2", "marinawindow1_256", 0);
	SetDynamicObjectMaterial(all_obj, 1, 13816, "lahills_safe1", "gry_roof", 0);
	SetDynamicObjectMaterial(all_obj, 0, 6988, "vgnfremnt1", "casinopillar1_256", 0);
	CreateDynamicObject(615, -664.762878, 1263.695313, 6.540771, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(11496, -616.321716, 1328.609131, 0.454405, -0.000022, -0.000037, -179.999680, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(11496, -628.871582, 1316.058838, 0.459410, 0.000007, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -665.168762, 1267.391724, 8.884886, 180.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(3934, -652.855164, 1291.463867, 13.478056, 0.000000, 0.000000, 180.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(11496, -618.372986, 1328.614014, 0.459410, 0.000022, 0.000037, -0.000037, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(11496, -628.866577, 1318.110107, 0.454405, -0.000007, 0.000000, -89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -667.177856, 1267.385620, 8.679901, 90.000008, 0.000000, 269.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(823, -680.524292, 1237.381226, 11.782103, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(762, -672.196289, 1259.305786, 8.147430, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -670.527771, 1267.380615, 8.684874, 90.000008, 0.000000, 269.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(11496, -612.871033, 1339.096558, 0.459410, 0.000029, 0.000000, 89.999908, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(3084, -666.031494, 1276.905762, 8.156065, -89.999992, 89.999992, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -671.842773, 1267.326172, 9.795013, 0.000000, 0.000000, 90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(1368, -668.470093, 1274.745728, 8.906065, 0.000000, 0.000007, 360.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 1716, "cj_seating", "CJ_SHINYWOOD", 0);
	CreateDynamicObject(11496, -612.866028, 1341.147827, 0.454405, -0.000029, 0.000000, -89.999908, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(3084, -666.031494, 1280.135376, 8.156065, -89.999992, 89.999992, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -686.766052, 1238.234131, 13.059906, 179.999985, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -686.413635, 1240.994141, 14.035246, -0.000014, -0.000001, -7.499960, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -686.496704, 1240.210327, 12.874908, 89.999985, -0.000001, -7.499960, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(669, -679.645203, 1256.160034, 8.329895, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(3084, -666.031494, 1283.345459, 8.156065, -89.999992, 89.999992, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(3934, -685.729065, 1245.546997, 16.000763, -0.000014, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(826, -668.179749, 1280.859253, 8.216064, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -675.517639, 1267.380615, 8.684874, 90.000008, 0.000000, 269.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(776, -668.727661, 1280.794922, 7.553435, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(803, -690.068542, 1236.318604, 12.514891, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -689.449890, 1238.580078, 12.879881, 89.999985, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(11714, -688.131226, 1243.241089, 13.701843, -0.000014, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 3603, "bevmans01_la", "wilsdoor_01_la", 0);
	CreateDynamicObject(617, -649.956055, 1307.989502, -0.383605, 0.000000, 0.000000, -15.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -689.949890, 1238.647095, 12.874908, 89.999985, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -690.355591, 1238.709473, 14.035246, -0.000014, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(1368, -668.450073, 1285.445190, 8.906065, 0.000000, 0.000007, 180.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 1716, "cj_seating", "CJ_SHINYWOOD", 0);
	all_obj = CreateDynamicObject(1368, -672.689880, 1277.944214, 8.906065, -0.000007, 0.000007, -89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 1716, "cj_seating", "CJ_SHINYWOOD", 0);
	CreateDynamicObject(11496, -644.871887, 1316.058838, 0.459410, 0.000000, 0.000000, 90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -678.508179, 1267.391724, 8.884886, 180.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(8947, -671.641357, 1279.154663, 5.162536, 0.000000, 0.000007, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 3979, "civic01_lan", "airportwall_256128", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	CreateDynamicObject(1359, -672.760010, 1280.168335, 8.876068, 0.000000, 0.000007, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -678.507507, 1269.741089, 8.684874, 90.000008, 0.000000, 179.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(11496, -644.866882, 1318.110107, 0.454405, 0.000000, 0.000000, 270.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1368, -672.689880, 1282.434570, 8.906065, -0.000007, 0.000007, -89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 1716, "cj_seating", "CJ_SHINYWOOD", 0);
	all_obj = CreateDynamicObject(8947, -671.636353, 1283.235962, 5.157530, 0.000000, 0.000007, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 3979, "civic01_lan", "airportwall_256128", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(984, -678.512878, 1273.555542, 9.795013, 0.000000, 0.000000, 180.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(618, -694.110107, 1236.172485, 11.883879, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(3171, -699.224976, 1219.239624, 12.232425, -0.272803, 9.082318, -94.183182, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(all_obj, 5, 65535, "none", "none", 0xFFFFFFFF);
	SetDynamicObjectMaterial(all_obj, 2, 65535, "none", "none", 0xFFFFFFFF);
	SetDynamicObjectMaterial(all_obj, 0, 65535, "none", "none", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(18762, -678.507507, 1274.722046, 8.684874, 90.000008, 0.000000, 179.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(813, -695.060425, 1237.196655, 13.907196, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(856, -686.844604, 1256.970825, 8.149963, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -678.512878, 1276.758179, 9.795013, 0.000000, 0.000000, 180.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(983, -695.102600, 1239.335938, 14.035246, -0.000014, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -694.906738, 1239.304443, 12.869902, 89.999985, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(813, -653.858704, 1313.172119, 2.496397, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -668.697693, 1295.013428, 8.884886, 180.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(822, -682.985718, 1269.678223, 7.840971, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -678.507507, 1279.712280, 8.684874, 90.000008, 0.000000, 179.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -670.747742, 1295.013062, 8.684874, 90.000008, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -678.508179, 1282.683105, 8.884886, 180.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -697.880859, 1239.695068, 13.059906, 179.999985, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(778, -681.471680, 1276.611206, 7.629881, 0.000000, 0.000000, 93.700005, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(983, -672.268799, 1294.998047, 9.855560, 0.000007, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(715, -638.779541, 1338.026489, 8.932495, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1499, -678.534119, 1284.673950, 8.197386, 0.000000, 0.000000, -90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(1232, -678.508179, 1285.152710, 9.084898, 360.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -678.508179, 1285.152710, 8.884886, 180.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(821, -681.965454, 1280.148438, 8.170959, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1499, -699.865540, 1239.957397, 12.353270, -0.000014, -0.000001, -7.499960, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	CreateDynamicObject(812, -685.396118, 1274.793457, 9.827209, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1232, -700.339722, 1240.018921, 13.259886, 360.000000, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -700.339722, 1240.018921, 13.059906, 179.999985, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(8947, -697.554016, 1246.564819, 9.322508, -0.000014, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 7555, "bballcpark1", "ws_carparknew2", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(19715, -657.936096, 1315.541870, 0.326735, 175.999908, 12.599995, -172.899994, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(13011, -697.621094, 1248.516479, 12.597839, -0.000014, -0.000001, -7.499960, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(823, -642.596985, 1334.731445, 0.930175, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(983, -675.468628, 1294.998047, 9.855560, 0.000007, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	//all_obj = CreateDynamicObject(975, -678.459778, 1290.076538, 9.736785, 0.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	all_obj = CreateDynamicObject(18762, -696.884216, 1253.390381, 13.059906, 0.000014, -179.999985, 82.500046, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(16667, -669.160278, 1302.597290, 2.859221, 0.000000, 0.000000, -153.700058, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 8421, "pirateland", "tislndrock01_128", 0);
	SetDynamicObjectMaterial(all_obj, 0, 6312, "beacliff_law2", "sm_rock2_desert", 0);
	all_obj = CreateDynamicObject(18762, -675.737732, 1295.013062, 8.684874, 90.000008, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(669, -675.238098, 1296.829834, 6.560180, 0.000000, 0.000000, 180.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(826, -667.010681, 1309.310669, 4.339867, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -698.823486, 1253.647583, 12.834898, 89.999985, -0.000001, 82.500038, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(672, -692.139648, 1268.806152, 8.803465, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1232, -678.508179, 1295.013428, 9.084898, 360.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -678.508179, 1295.013428, 8.884886, 180.000000, 0.000000, 89.999977, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(19715, -663.991028, 1314.293213, 1.712710, 177.999893, 12.999996, -172.899994, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(1281, -695.662720, 1262.605957, 9.593138, 0.000000, 0.000000, -5.299997, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(983, -700.186523, 1253.815552, 14.035246, -0.000014, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	//all_obj = CreateDynamicObject(975, -705.212158, 1240.730713, 13.872680, 0.000000, 0.000000, -7.499961, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	CreateDynamicObject(800, -698.998474, 1256.726318, 10.069975, 0.000000, 0.000000, 42.299999, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -701.407959, 1253.999146, 12.834898, 89.999985, -0.000001, 82.500038, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(9321, -703.067078, 1251.945435, 13.787596, -0.000014, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(618, -647.547974, 1338.111328, 1.821899, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19715, -684.450256, 1290.562988, 7.174371, 179.000107, -2.000008, -46.700016, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(1281, -691.320129, 1280.621338, 9.353117, 0.000000, 0.000000, 48.899994, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(826, -663.620544, 1322.360718, 3.549865, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(983, -704.924866, 1254.440063, 14.035246, -0.000014, -0.000001, -97.499962, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(733, -662.931091, 1324.793213, 2.081207, 0.000000, 0.000000, -35.600006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(823, -676.657166, 1307.969604, 6.317238, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1232, -710.105469, 1241.301880, 13.259886, 180.000015, -179.999985, 82.500046, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -710.105469, 1241.301880, 13.059906, 0.000014, -179.999985, 82.500046, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(17071, -657.668274, 1332.168945, 2.194946, 0.000000, 0.000000, 70.500076, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 16102, "des_cen", "des_rocky1_dirt1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 16103, "des_ne", "des_yelrock", 0);
	all_obj = CreateDynamicObject(18762, -709.834717, 1243.287598, 12.859892, 89.999992, 26.368643, -33.868607, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(19715, -673.616882, 1312.612061, 3.967293, -179.900009, 14.899996, -172.899994, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(825, -669.871765, 1318.467773, 5.180611, 0.000000, 0.000000, 15.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -706.335571, 1254.647949, 12.834898, 89.999985, -0.000001, 82.500038, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(708, -702.586731, 1262.120361, 8.411041, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -709.298889, 1247.159058, 13.985014, -0.000014, -0.000001, -7.499960, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -709.090332, 1248.744629, 13.985014, -0.000014, -0.000001, -7.499960, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -709.221802, 1247.984985, 12.864897, 89.999992, 26.368643, -33.868607, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1281, -699.701050, 1270.649658, 9.523132, 0.000000, 0.000000, 100.400002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(800, -660.893860, 1331.875732, 4.518858, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -708.570129, 1252.932373, 12.864897, 89.999992, 26.368643, -33.868607, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(825, -686.832153, 1297.846558, 9.160614, 0.000000, 0.000000, 15.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -653.835144, 1318.910645, -41.650085, 0.000000, 180.000000, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -708.316101, 1254.894165, 13.059906, 0.000014, -179.999985, 82.500046, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -667.924133, 1301.421997, -41.650085, 0.000000, 180.000000, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(707, -698.188232, 1279.639893, 8.237579, 0.000000, 0.000000, 45.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -655.844910, 1318.850708, -41.855103, 89.999992, 2.098596, -89.998573, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -653.945740, 1321.912231, -41.855103, 89.999992, 89.999992, -87.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -669.917114, 1301.348755, -41.845093, 89.999992, -177.901398, -89.998604, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(19715, -692.572205, 1292.883301, 7.649711, 179.700150, -2.200008, -36.600014, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(18762, -668.028198, 1304.409912, -41.845093, 89.999992, -89.999992, -87.899956, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(800, -706.858154, 1264.128052, 9.117552, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(703, -714.978271, 1244.628662, 10.401823, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -654.087341, 1325.101685, -40.724976, -0.000006, 0.000023, 2.100028, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(17071, -702.767761, 1275.176270, 7.934967, 0.000000, 0.000000, 161.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 16102, "des_cen", "des_rocky1_dirt1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 16103, "des_ne", "des_yelrock", 0);
	all_obj = CreateDynamicObject(19715, -682.500549, 1311.581543, 6.328997, -178.199966, 14.799996, -172.899994, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(805, -698.042358, 1286.525146, 9.435333, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(823, -689.597107, 1301.694824, 9.252470, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -660.403381, 1318.687378, -40.724976, -0.000014, 0.000007, -87.899948, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -668.179810, 1308.301636, -40.724976, 0.000000, 0.000000, -177.899948, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(615, -689.732178, 1301.931641, 8.087585, 0.000000, 0.000000, 90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(983, -711.470581, 1259.952148, 13.485228, 0.000000, 0.000000, 138.599991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -660.551270, 1318.673218, -41.850098, 89.999992, 2.098596, -89.998573, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -654.128479, 1326.897827, -41.855103, 89.999992, 89.999992, -87.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -712.528442, 1258.752808, 13.485228, 0.000000, 0.000000, 138.599991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -668.211304, 1309.406006, -41.845093, 89.999992, -89.999992, -87.899956, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -661.992493, 1318.629150, -40.724976, -0.000014, 0.000007, -87.899948, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -674.453003, 1301.166870, -40.724976, 0.000007, 0.000007, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -673.999878, 1301.199341, -41.850098, 89.999992, -177.901398, -89.998604, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(813, -681.058228, 1317.614136, 9.009979, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(826, -662.035339, 1340.314087, 4.150786, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -668.296997, 1311.500366, -40.724976, 0.000000, 0.000000, -177.899948, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -714.853760, 1255.986206, 13.454895, 0.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -676.051697, 1301.108276, -40.724976, 0.000007, 0.000007, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -716.171387, 1254.488525, 13.294891, 89.999992, 36.873959, -78.273964, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(17071, -676.929443, 1326.618774, 6.104948, 0.000000, 0.000000, -84.799942, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 16102, "des_cen", "des_rocky1_dirt1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 16103, "des_ne", "des_yelrock", 0);
	all_obj = CreateDynamicObject(18762, -654.311218, 1331.884277, -41.855103, 89.999992, 89.999992, -87.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -668.394409, 1314.402466, -41.845093, 89.999992, -89.999992, -87.899956, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1499, -716.321838, 1257.333252, 12.813995, -0.000004, 0.000004, -41.400005, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	CreateDynamicObject(826, -694.496338, 1301.957642, 9.450592, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -665.547546, 1318.490112, -41.850098, 89.999992, 2.098596, -89.998573, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(803, -721.417908, 1242.968872, 13.045532, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -716.713867, 1257.626709, 13.454895, 0.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -719.411743, 1250.805786, 14.415007, 0.000000, 0.000000, -41.400013, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -719.307617, 1250.925659, 13.289916, 89.999992, 36.873959, -78.273964, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1281, -710.879761, 1272.179932, 9.963133, 0.000000, 0.000000, 16.199989, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -668.461914, 1316.381714, -41.850098, 89.999992, -89.999992, -87.899956, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -678.986267, 1301.016602, -41.850098, 89.999992, -177.901398, -89.998604, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -714.174622, 1266.544922, 13.434996, 0.000000, 0.000000, 48.599987, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(3171, -730.889587, 1200.937744, 9.070292, -4.772519, 6.482475, -124.492699, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(all_obj, 5, 65535, "none", "none", 0xFFFFFFFF);
	SetDynamicObjectMaterial(all_obj, 2, 65535, "none", "none", 0xFFFFFFFF);
	SetDynamicObjectMaterial(all_obj, 0, 65535, "none", "none", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(18762, -717.456177, 1258.281860, 13.454895, 0.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(691, -676.193787, 1329.931274, 4.926208, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(3640, -661.479004, 1329.172729, -37.918762, -0.000007, 0.000007, -87.899971, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19715, -698.909973, 1297.588745, 8.017819, -179.899811, -1.800009, -36.600014, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(618, -669.065552, 1339.809326, 4.997893, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -718.190979, 1258.930664, 13.454895, 0.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -668.545227, 1318.371582, -41.650085, 0.000000, 180.000000, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -654.496765, 1336.276123, -40.724976, -0.000006, 0.000023, 2.100028, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(19715, -692.411560, 1309.301880, 7.951875, 177.899933, 2.099999, -155.999985, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(826, -688.526306, 1315.837158, 9.080597, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -722.600891, 1247.189819, 13.289916, 89.999992, 36.873959, -78.273964, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -654.493958, 1336.870972, -41.855103, 89.999992, 89.999992, -87.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -723.926697, 1245.695801, 13.454895, 0.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -681.964111, 1300.907471, -41.650085, 0.000000, 180.000000, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(822, -703.649353, 1293.327759, 9.315550, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(856, -716.073914, 1267.345703, 8.885437, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(8947, -661.124023, 1330.419189, -45.402527, 0.000000, 0.000014, 2.100008, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 10355, "haight1_sfs", "drivetile_02", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(1499, -725.434387, 1246.997925, 12.813995, -0.000004, 0.000004, -41.400005, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	CreateDynamicObject(825, -709.119690, 1286.469849, 9.892181, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -654.620056, 1340.448608, -41.850098, 89.999992, 89.999992, -87.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(19715, -697.691711, 1306.944092, 8.103599, 177.899933, 2.099999, -155.999985, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(1232, -725.786865, 1247.335938, 13.654907, 180.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -725.786865, 1247.335938, 13.454895, 0.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(8947, -675.218079, 1312.939331, -45.397522, 0.000000, 0.000014, 2.100008, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 7555, "bballcpark1", "ws_carparknew2", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	//all_obj = CreateDynamicObject(975, -682.174683, 1305.828125, -40.834595, 0.000007, 0.000007, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	all_obj = CreateDynamicObject(18762, -690.199890, 1320.580200, 10.329895, 180.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(800, -714.002686, 1278.656006, 10.046751, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -654.697571, 1342.445679, -41.650085, 0.000000, 180.000000, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(3928, -722.408875, 1262.579346, 17.583344, 0.000000, 0.000000, 48.599987, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(823, -676.283875, 1340.103760, 6.882384, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -692.198303, 1320.661499, 10.149902, 270.000000, 0.000000, 267.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(615, -716.972961, 1276.036987, 8.637602, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -682.324829, 1310.751465, -41.650085, 0.000000, 180.000000, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(826, -696.926453, 1314.797363, 9.450592, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(672, -695.417969, 1318.381226, 9.930725, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19715, -706.114380, 1302.938599, 8.379848, -179.899811, -1.800009, -36.600014, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(800, -711.029968, 1297.189087, 10.206114, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -689.843689, 1327.170044, 11.265013, 0.000000, 0.000000, 357.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -722.568970, 1273.944946, 13.434996, 0.000000, 0.000000, 48.599987, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	//all_obj = CreateDynamicObject(975, -729.476807, 1250.599365, 14.302673, 0.000000, 0.000000, -41.400005, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	all_obj = CreateDynamicObject(18762, -696.243591, 1320.865479, 10.149902, 270.000000, 0.000000, 267.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -696.683044, 1320.838379, 11.265013, 0.000000, 0.000000, 267.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(3608, -724.071106, 1265.855835, 4.334533, -0.000004, 0.000004, -41.400005, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19715, -703.997681, 1311.051758, 8.386072, -179.399841, 2.699990, 122.699989, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(984, -698.271729, 1320.917603, 11.265013, 0.000000, 0.000000, 267.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(825, -700.780457, 1317.494263, 10.101866, 0.000000, 0.000000, -39.499981, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(856, -724.283997, 1274.736694, 8.885437, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18980, -689.588318, 1332.552856, 10.154907, 90.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(13011, -730.806702, 1260.540405, 14.198181, 0.000004, 0.000004, 48.599976, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(768, -679.328430, 1342.850830, 6.444884, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -701.226990, 1321.118896, 10.149902, 270.000000, 0.000000, 267.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1232, -733.167969, 1253.843750, 13.654907, 180.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -733.167969, 1253.843750, 13.454895, 0.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1499, -682.421326, 1311.242065, -42.363953, 0.000000, 0.000007, 92.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(18762, -682.416016, 1313.239990, -41.650085, 0.000000, 180.000000, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(726, -720.970276, 1291.675049, 10.321014, 0.000000, 0.000000, 20.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(825, -715.250610, 1302.773193, 10.651869, 0.000000, 0.000000, -85.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(17071, -721.346558, 1292.848145, 10.124938, 0.000000, 0.000000, 70.999992, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 16102, "des_cen", "des_rocky1_dirt1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 16103, "des_ne", "des_yelrock", 0);
	all_obj = CreateDynamicObject(983, -729.443481, 1275.796387, 13.485228, 0.000000, 0.000000, 138.599991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -704.173096, 1321.266968, 10.329895, 180.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -735.395691, 1255.807861, 13.279907, 89.999992, 146.522858, -97.922874, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(856, -681.834106, 1344.631470, 7.248015, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1499, -704.659302, 1321.272827, 9.642210, 0.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(19715, -713.288391, 1308.648315, 8.762907, 179.100159, -2.200009, -12.900002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(983, -735.885925, 1256.243286, 14.465239, 0.000000, 0.000000, 48.599987, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -689.197632, 1339.923584, 11.265013, 0.000000, 0.000000, 357.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -736.331177, 1256.627808, 13.284912, 89.999992, 146.522858, -97.922874, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(618, -737.066162, 1252.445557, 12.178160, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -682.642395, 1319.328247, -40.724976, 0.000000, -0.000007, -177.899902, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(1232, -706.640076, 1321.391968, 10.529907, 360.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -706.640076, 1321.391968, 10.329895, 180.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(8947, -696.461304, 1332.681030, 6.622497, 0.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 3603, "bevmans01_la", "sjmlahus29", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	CreateDynamicObject(808, -738.446045, 1254.567993, 13.950012, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19715, -711.606506, 1316.237305, 8.578316, -176.999969, 1.300000, -163.500000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(984, -661.094666, 1342.200928, -40.724976, -0.000014, 0.000007, -87.899948, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -737.099365, 1266.400146, 14.415007, 0.000000, 0.000000, -41.400013, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -736.980530, 1266.506592, 13.289916, 89.999992, 36.873959, -78.273964, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -739.486572, 1259.418091, 14.465239, 0.000000, 0.000000, 48.599987, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -740.074219, 1259.927979, 13.284912, 89.999992, 146.522858, -97.922874, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	//all_obj = CreateDynamicObject(975, -711.546387, 1321.695679, 11.151611, 0.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	all_obj = CreateDynamicObject(1368, -701.780396, 1333.652832, 10.351042, -0.000018, 0.000075, -2.999980, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 1716, "cj_seating", "CJ_SHINYWOOD", 0);
	CreateDynamicObject(812, -741.256042, 1257.497437, 13.950012, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(8947, -675.843872, 1329.878296, -45.402527, 0.000000, 0.000014, 2.100008, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 7555, "bballcpark1", "ws_carparknew2", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(18980, -682.896912, 1326.217773, -41.845093, 89.999992, -89.999992, -87.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -740.274292, 1262.770264, 13.289916, 89.999992, 36.873959, -78.273964, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -735.791748, 1279.277588, 14.389923, 90.000008, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(3934, -675.809021, 1333.851196, -42.358948, 0.000007, 0.000007, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(823, -725.427979, 1301.951782, 10.561186, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -741.577454, 1261.256714, 13.454895, 0.000000, 179.999985, -131.400009, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1359, -704.005127, 1333.699097, 10.321043, 0.000068, 0.000018, 86.999771, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -737.185913, 1278.410522, 14.469908, 180.000000, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18980, -667.654297, 1341.972290, -41.850098, 89.999992, -177.901398, -89.998604, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(19715, -721.348694, 1309.802612, 8.942100, 178.200104, 0.499990, -12.900002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(18980, -683.006531, 1329.345947, -41.840088, 89.999992, -89.999992, -87.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(825, -701.885071, 1338.222046, 9.676054, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19543, -653.571106, 1325.901001, -73.596985, 90.000000, 0.000014, 92.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(3084, -703.770020, 1336.163818, 9.596037, 270.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1368, -706.264587, 1333.888184, 10.351042, -0.000018, 0.000075, -2.999980, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 1716, "cj_seating", "CJ_SHINYWOOD", 0);
	all_obj = CreateDynamicObject(984, -683.110046, 1332.088745, -40.724976, 0.000000, -0.000007, -177.899902, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18980, -671.431213, 1341.838867, -41.845093, 89.999992, -177.901398, -89.998604, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(782, -703.627686, 1337.377075, 9.467590, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -739.989380, 1276.633545, 14.389923, 90.000008, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1232, -716.477051, 1321.890747, 10.529907, 360.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(703, -742.484985, 1267.352173, 11.926177, 0.000000, 0.000000, 45.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -716.477051, 1321.890747, 10.329895, 180.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -740.863525, 1276.037231, 15.515013, 0.000003, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -673.846313, 1341.733643, -40.724976, -0.000014, 0.000007, -87.899948, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(3084, -703.606262, 1339.388550, 9.596037, 270.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(8572, -740.921692, 1280.300171, 16.106049, 0.000003, 0.000006, -57.799927, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -683.226868, 1335.278931, -40.724976, 0.000000, -0.000007, -177.899902, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(825, -719.776917, 1320.107422, 10.101866, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(825, -706.045410, 1337.871704, 9.676054, 0.000000, 0.000000, 180.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -677.033936, 1341.616821, -40.724976, -0.000014, 0.000007, -87.899948, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(3934, -738.079712, 1291.176880, 17.343506, 0.000003, 0.000006, 32.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -744.211426, 1273.975220, 14.389923, 90.000008, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(669, -730.480286, 1305.608032, 10.171783, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(767, -720.897766, 1321.367065, 9.353178, 0.000000, 0.000000, 15.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -716.191650, 1328.663940, 11.265013, 0.000000, 0.000000, 357.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -745.884460, 1272.933105, 14.469908, 180.000000, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(19715, -729.068542, 1309.824341, 8.929815, 178.200104, 0.499990, -12.900002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(13694, -738.304016, 1291.626953, 8.414610, -0.000006, 0.000003, -57.799923, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 10398, "countryclub_sfs", "hc_wall2", 0);
	all_obj = CreateDynamicObject(19543, -653.916565, 1335.465210, -73.596985, 90.000000, 0.000014, 92.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 12866, "ce_ground07", "desgrassbrn", 0);
	CreateDynamicObject(3928, -698.467957, 1352.759277, 13.458557, 0.000000, 0.000000, 267.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -728.375549, 1316.409302, 13.904907, 180.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(11714, -741.697815, 1290.787109, 15.116058, 0.000003, 0.000006, 32.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 3603, "bevmans01_la", "wilsdoor_01_la", 0);
	CreateDynamicObject(1281, -684.668335, 1362.268921, 3.444488, 0.000000, 0.000000, 36.900002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -683.447632, 1341.390625, -41.650085, 0.000000, 180.000000, 92.099983, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -748.326233, 1271.383423, 13.972990, 80.200020, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1622, -743.487610, 1287.341309, 16.935999, 0.000000, 0.000000, 342.203918, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	all_obj = CreateDynamicObject(983, -748.850952, 1271.046265, 15.032408, -10.000000, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18980, -715.865356, 1333.864136, 10.154907, 90.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -727.925781, 1318.369751, 13.649902, 90.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(800, -722.671875, 1325.791260, 10.261627, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(12950, -714.420349, 1336.783447, 10.082640, 0.000000, 0.000000, 357.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -749.873657, 1270.407104, 13.651367, 80.200020, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1255, -687.176758, 1363.912231, 9.922636, 0.000000, 0.000000, 31.600000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -726.938477, 1322.736084, 14.795042, 0.000000, -0.000007, 167.099960, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -726.811829, 1323.234497, 13.649902, 90.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1232, -751.646790, 1269.304565, 13.639923, 360.000000, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -751.646790, 1269.304565, 13.439909, 180.000000, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(825, -731.582214, 1315.356323, 10.462767, 0.000000, 0.000000, 135.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19715, -734.869507, 1310.281494, 9.295131, 177.100067, -11.400004, -12.900002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(984, -743.519714, 1295.212280, 15.515013, 0.000015, -0.000000, 212.200027, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(823, -720.550964, 1333.541870, 8.875000, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -725.695068, 1328.108643, 13.649902, 90.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -715.546570, 1341.398193, 11.265013, 0.000000, 0.000000, 357.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(715, -717.264587, 1340.936768, 16.708954, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(1255, -690.352600, 1366.173218, 9.922636, 0.000000, 0.000000, 87.300011, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -734.158264, 1317.761719, 14.795042, 0.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -724.581116, 1332.972656, 13.649902, 90.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -724.441650, 1333.635376, 14.795042, 0.000000, -0.000007, 167.099960, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	//all_obj = CreateDynamicObject(975, -754.265930, 1273.467407, 14.252685, 0.000000, 0.000000, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	CreateDynamicObject(700, -735.811035, 1315.533813, 10.516418, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(822, -741.690430, 1305.721558, 12.253569, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -745.717529, 1298.528687, 14.384918, 89.999992, -156.632507, -171.167404, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1255, -693.092651, 1367.093384, 9.922636, 0.000000, 0.000000, 87.300011, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -723.559753, 1337.408691, 13.654907, 90.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -746.778625, 1300.211182, 14.469908, -0.000006, -179.999985, -57.799927, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -723.120972, 1339.354248, 13.904907, 180.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1281, -694.176208, 1366.813232, 3.444488, 0.000000, 0.000000, 90.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(3741, -710.412231, 1352.764038, 5.802337, 0.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 3, 5461, "glenpark6d_lae", "tiledwall01_LA", 0);
	all_obj = CreateDynamicObject(3771, -710.412231, 1352.764038, 5.802337, 0.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5631, "apartmentalpha", "ws_railing1", 0);
	CreateDynamicObject(617, -746.393738, 1302.619019, 11.810729, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -748.477478, 1299.177368, 14.384918, 89.999992, -156.632507, -81.167404, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1232, -756.890259, 1277.630859, 13.639923, 360.000000, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -756.890259, 1277.630859, 13.439909, 180.000000, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(9321, -752.252075, 1292.596924, 15.247589, -0.000006, 0.000003, -57.799923, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19715, -742.770569, 1312.174438, 10.890479, 177.100067, -11.400004, -12.900002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(822, -739.670166, 1317.883179, 10.873229, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(3934, -732.943176, 1329.378418, 13.181059, 0.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(3741, -710.402222, 1352.774048, -0.897674, 0.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 3, 5461, "glenpark6d_lae", "tiledwall01_LA", 0);
	SetDynamicObjectMaterial(all_obj, 2, 14537, "pdomebar", "club_floor2_sfwTEST", 0);
	all_obj = CreateDynamicObject(3771, -710.402222, 1352.774048, -0.897674, 0.000000, 0.000000, 177.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5631, "apartmentalpha", "ws_railing1", 0);
	all_obj = CreateDynamicObject(8947, -732.430664, 1329.409180, 10.127532, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 7555, "bballcpark1", "ws_carparknew2", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(18980, -740.072205, 1319.089355, 13.644897, 90.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(8947, -732.445618, 1329.433105, 7.827514, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 6487, "councl_law2", "rodeo3sjm", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(1499, -757.968750, 1279.293213, 12.794006, 0.000003, 0.000006, -57.799927, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(984, -752.088684, 1296.844482, 15.515013, 0.000015, -0.000000, 122.200027, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -758.195862, 1279.704102, 13.439909, 180.000000, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);

	CreateDynamicObject(1281, -700.486450, 1366.802490, 10.164488, 0.000000, 0.000000, 59.699997, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -752.560120, 1296.593506, 14.389923, 89.999992, -156.632507, -81.167404, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(800, -748.114502, 1306.539551, 14.395355, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(8947, -760.068726, 1272.995972, 8.733366, -10.199998, 0.000006, 122.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 14387, "dr_gsnew", "mp_stonefloor", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(984, -753.434265, 1295.997192, 15.515013, 0.000015, -0.000000, 122.200027, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -759.266846, 1281.396729, 13.179901, 270.000000, 0.000006, 212.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -759.840393, 1282.191162, 14.355223, 0.000007, 0.000012, 32.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -729.830200, 1340.880371, 14.795042, 0.000000, -0.000007, 257.099976, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(671, -758.774658, 1287.614014, 12.569946, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -756.782166, 1293.935181, 14.389923, 89.999992, -156.632507, -81.167404, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(700, -744.899170, 1318.423340, 12.335356, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -745.066101, 1320.260010, 14.795042, 0.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -758.455200, 1292.893066, 14.469908, -0.000006, -179.999985, -57.799927, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(805, -746.712036, 1318.550415, 13.389430, 0.000000, 0.000000, 33.299995, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -761.931213, 1285.627808, 13.179901, 270.000000, 0.000006, 212.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -762.392883, 1286.244995, 14.355223, 0.000007, 0.000012, 32.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -760.896973, 1291.343384, 13.972990, 80.200035, -0.000040, 122.200081, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -760.896973, 1291.343384, 12.972990, 80.200035, -0.000040, 122.200081, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -761.421692, 1291.006226, 15.032408, -9.999985, -0.000000, 122.200027, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(19715, -750.829956, 1314.116333, 12.733912, 177.100067, -11.000006, -12.900002, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(18762, -763.150818, 1287.556396, 13.174896, 270.000000, 0.000006, 212.200073, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -762.444397, 1290.367065, 13.651367, 80.200035, -0.000040, 122.200081, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -762.444397, 1290.367065, 12.651367, 80.200035, -0.000040, 122.200081, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18980, -734.815125, 1342.044556, 13.644897, 90.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(669, -759.138916, 1299.793091, 13.229948, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -764.217529, 1289.264526, 13.439909, -0.000006, -179.999985, -57.799927, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(822, -755.367493, 1311.443726, 14.454559, 0.000000, 0.000000, 56.599972, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(17071, -761.035645, 1300.102051, 13.364958, 0.000000, 0.000000, 158.099991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 16102, "des_cen", "des_rocky1_dirt1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 16103, "des_ne", "des_yelrock", 0);
	CreateDynamicObject(1359, -745.887207, 1329.669678, 13.826048, 0.000134, 0.000034, 76.999626, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(14400, -750.992310, 1322.662354, 13.251068, 0.000000, 0.000000, -169.400040, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -751.779846, 1321.769165, 13.904907, 180.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1368, -748.079163, 1330.248657, 13.856047, -0.000034, 0.000142, -12.999979, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 1716, "cj_seating", "CJ_SHINYWOOD", 0);
	all_obj = CreateDynamicObject(8947, -746.798523, 1332.700073, 10.127532, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 6487, "councl_law2", "rodeo3sjm", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	all_obj = CreateDynamicObject(1499, -753.694946, 1322.307251, 13.376463, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(18762, -754.197327, 1322.322876, 13.904907, 180.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -742.278076, 1343.730835, 14.795042, 0.000000, -0.000007, 257.099976, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(805, -757.426086, 1320.652588, 14.329437, 0.000000, 0.000000, 33.299995, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -756.424316, 1322.833984, 13.649902, 90.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1255, -737.521423, 1350.418823, 7.182647, 0.000000, 0.000000, -1.999973, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(983, -757.537964, 1323.104004, 14.847534, 0.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(19715, -761.538391, 1315.795776, 12.921705, 179.299988, 6.199999, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(618, -758.537415, 1322.060669, 13.465239, 0.000000, 0.000000, 180.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(672, -765.177673, 1310.125610, 14.050903, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -758.914795, 1323.403809, 13.644897, 90.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1255, -738.501587, 1352.814941, 7.182647, 0.000000, 0.000000, 25.100025, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(1232, -760.864746, 1323.849731, 14.104887, 360.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -760.864746, 1323.849731, 13.904907, 180.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(782, -771.392700, 1301.682861, 12.640898, 0.000000, 0.000000, 45.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(821, -768.186462, 1310.102905, 13.320068, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(1281, -738.366272, 1356.222412, 7.404510, 0.000000, 0.000000, -14.800004, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(14400, -762.582214, 1322.701294, 13.871048, 0.000000, 0.000000, -15.200028, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(822, -772.393311, 1306.386597, 13.239990, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(1255, -737.893250, 1361.568237, 7.182647, 0.000000, 0.000000, -31.499975, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(14400, -764.491333, 1325.095215, 13.231047, 0.000000, 0.000000, -15.200028, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	//all_obj = CreateDynamicObject(975, -765.673584, 1325.000610, 14.701263, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	all_obj = CreateDynamicObject(19715, -768.830444, 1318.863892, 12.034708, 180.000000, 6.999996, -0.899992, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(19715, -768.830444, 1318.863892, 12.034708, 180.000000, 6.999996, -0.899992, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(18980, -753.492188, 1346.326782, 13.649902, 90.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(14400, -766.644104, 1326.092773, 13.391052, 0.000000, 0.000000, -15.200028, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -754.725342, 1346.582275, 14.795042, 0.000000, -0.000007, 257.099976, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(6056, -774.959045, 1310.915283, 14.616058, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(all_obj, 2, 12843, "cunte_lik", "crencouwall1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 1736, "cj_ammo", "CJ_SPEAKER_c", 0);
	SetDynamicObjectMaterial(all_obj, 0, 6487, "councl_law2", "stonewall2_la", 0);
	all_obj = CreateDynamicObject(8947, -761.166260, 1335.990601, 10.127532, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 2, 6487, "councl_law2", "rodeo3sjm", 0);
	SetDynamicObjectMaterial(all_obj, 1, 12866, "ce_ground07", "desgrassbrn", 0);
	CreateDynamicObject(826, -774.533264, 1312.268188, 12.970947, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(7666, -776.019653, 1310.771973, 16.972443, 60.495602, -89.999985, 89.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterialText(all_obj, 0, "TIERRA ROBADA", 140, "Georgia", 63, 1, 0xFF6B3700, 0, 1);
	all_obj = CreateDynamicObject(7666, -776.019653, 1310.771973, 16.432465, 60.495602, -89.999985, 89.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterialText(all_obj, 0, "V I L L A G E", 140, "Georgia", 90, 1, 0xFF6B3700, 0, 1);
	all_obj = CreateDynamicObject(1232, -770.475647, 1326.051270, 14.104887, 360.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -770.475647, 1326.051270, 13.904907, 180.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -770.037476, 1328.008667, 13.649902, 89.999992, 89.999992, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(9321, -762.112000, 1343.383545, 14.571075, 0.000000, 0.000000, 257.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(984, -769.174072, 1331.864746, 14.795042, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(984, -759.404724, 1347.653198, 14.795042, 0.000000, -0.000007, 257.099976, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -770.880188, 1328.716797, 13.669891, 180.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -768.923523, 1332.873413, 13.649902, 89.999992, 89.999992, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -767.806763, 1337.747559, 13.649902, 89.999992, 89.999992, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(1499, -772.814209, 1329.171509, 12.956480, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFFFFFFF);
	all_obj = CreateDynamicObject(19715, -777.866943, 1319.524414, 11.609382, 180.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(18762, -773.277954, 1329.266357, 13.669891, 180.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -766.675476, 1342.773804, 14.795042, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(672, -775.135071, 1327.865234, 13.114897, 0.000000, 0.000000, 180.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(18762, -766.692810, 1342.611572, 13.649902, 89.999992, 89.999992, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -765.671448, 1347.047607, 13.654907, 89.999992, 89.999992, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(19715, -779.728394, 1322.166748, 11.619382, 180.000000, 0.000000, -2.799999, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(18762, -776.158569, 1329.926270, 13.484892, 270.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -776.332336, 1330.045532, 14.657530, 0.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -765.219788, 1348.997681, 13.904907, 180.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(956, -772.323730, 1338.100952, 13.361054, 0.000000, 0.100000, 347.016602, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	all_obj = CreateDynamicObject(18762, -769.716187, 1342.529297, 13.449890, 89.999992, 89.999992, -12.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(983, -777.892151, 1330.402222, 14.657530, 0.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(all_obj, 5, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -778.298462, 1330.415039, 13.479887, 270.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(2614, -775.695129, 1339.248169, 17.594362, 2.000000, 0.000000, 346.923615, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	all_obj = CreateDynamicObject(984, -773.065735, 1343.355469, 14.575041, 0.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(1359, -775.777039, 1338.608765, 13.626036, 0.000142, 0.000036, 76.999603, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	all_obj = CreateDynamicObject(19715, -782.311768, 1326.047852, 11.629383, 180.000000, 0.000000, -2.799999, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	all_obj = CreateDynamicObject(1232, -781.174011, 1331.073608, 13.869902, 180.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -781.174011, 1331.073608, 13.669891, 180.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(1478, -781.553162, 1330.353149, 13.624161, 0.000000, 359.899994, 315.890472, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	all_obj = CreateDynamicObject(1368, -777.968994, 1339.187744, 13.656065, -0.000036, 0.000150, -12.999979, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 1716, "cj_seating", "CJ_SHINYWOOD", 0);
	CreateDynamicObject(361, -779.301392, 1339.935791, 13.048415, 69.400093, 0.200000, 227.316620, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	CreateDynamicObject(360, -779.927917, 1339.947266, 13.630302, 1.600002, 255.000015, 253.925812, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	all_obj = CreateDynamicObject(19715, -785.063232, 1329.967285, 11.599382, 180.000000, 0.000000, 42.200001, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 0, 5109, "docks_las2", "sjmndukwal3", 0);
	CreateDynamicObject(1697, -776.230286, 1348.056030, 17.543772, 3.999998, 0.200000, 75.840225, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	//all_obj = CreateDynamicObject(975, -785.943604, 1332.309814, 14.481262, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 4
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 5449, "chicanotr1_lae", "eb_firesc1_LAe2", 0xFFAAAAAA);
	SetDynamicObjectMaterial(all_obj, 0, 1736, "cj_ammo", "CJ_Black_metal", 0);
	CreateDynamicObject(3614, -776.124451, 1350.480103, 8.692687, 0.000000, 0.000000, 167.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0
	CreateDynamicObject(18664, -782.955933, 1341.134033, 14.413470, 2.800011, 360.000000, 79.143593, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	all_obj = CreateDynamicObject(984, -781.555969, 1345.299683, 14.575041, 0.000000, 0.000000, 77.100006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(1232, -790.795227, 1333.276611, 13.869902, 180.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -790.795227, 1333.276611, 13.669891, 180.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -790.356384, 1335.238647, 13.449890, 89.999992, 89.999992, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(8674, -778.321167, 1356.190674, 14.033558, 68.300095, 90.599960, 345.514740, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	all_obj = CreateDynamicObject(984, -789.433350, 1339.171753, 14.575041, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -789.240417, 1340.112427, 13.449890, 89.999992, 89.999992, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(984, -789.075195, 1340.732666, 14.575041, 0.000000, 0.000000, -12.899991, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 10
	SetDynamicObjectMaterial(all_obj, 9, 5631, "apartmentalpha", "ws_railing1", 0);
	SetDynamicObjectMaterial(all_obj, 8, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 7, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 6, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 5, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(all_obj, 0, 19962, "samproadsigns", "materialtext1", 0);
	all_obj = CreateDynamicObject(18762, -785.790894, 1346.209229, 13.449890, 89.999992, 89.999992, -12.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -788.183289, 1344.724487, 13.449890, 89.999992, 89.999992, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	all_obj = CreateDynamicObject(18762, -787.709717, 1346.658325, 13.669891, 360.000000, 180.000000, -102.899986, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(all_obj, 1, 4829, "airport_las", "sjmlahus28", 0);
	SetDynamicObjectMaterial(all_obj, 0, 4829, "airport_las", "sjmlahus28", 0);
	CreateDynamicObject(669, -792.162781, 1338.565552, 12.690917, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 0