	new azmax;
	azmax = CreateDynamicObject(983, -2582.802002, 166.264313, 4.007215, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(azmax, 5, 6284, "bev_law2", "glass_fence_64hv", 0);
	SetDynamicObjectMaterial(azmax, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(13646, -2586.588379, 164.261414, 10.563470, 89.999992, 90.000000, -89.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(azmax, 1, 10765, "airportgnd_sfse", "white", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(13646, -2586.928711, 164.251419, 10.563470, 89.999992, 90.000000, -89.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(azmax, 1, 10765, "airportgnd_sfse", "black64", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(2431, -2586.238281, 168.038635, 6.501795, -14.999999, 0.000023, 0.000006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(azmax, 2, 14859, "gf1", "mp_apt1_pos3", 0);
	SetDynamicObjectMaterial(azmax, 1, 14859, "gf1", "mp_apt1_pos2", 0);
	SetDynamicObjectMaterial(azmax, 0, 14859, "gf1", "mp_apt1_pos1", 0);
	azmax = CreateDynamicObject(983, -2585.981934, 163.104248, 4.007215, 0.000000, 0.000000, 450.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(azmax, 5, 6284, "bev_law2", "glass_fence_64hv", 0);
	SetDynamicObjectMaterial(azmax, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(19445, -2585.318604, 167.978043, 3.155647, 90.000000, 0.000000, 90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(azmax, 0, 1809, "cj_hi_fi", "CJ_speaker_6", 0);
	azmax = CreateDynamicObject(2431, -2586.238281, 168.038635, 5.301795, -14.999999, 0.000023, 0.000006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(azmax, 2, 3083, "billbox", "Sprunk_postersign1", 0);
	SetDynamicObjectMaterial(azmax, 1, 6282, "beafron2_law2", "hollysign02_LAw", 0);
	SetDynamicObjectMaterial(azmax, 0, 14859, "gf1", "mp_apt1_pos4", 0);
	azmax = CreateDynamicObject(7666, -2589.174561, 163.586395, 10.738050, 60.495598, -90.000061, -179.999649, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterialText(azmax, 0, "MAX", 140, "Arial", 199, 0, 0xFFFFFFFF, 0, 1);
	azmax = CreateDynamicObject(2431, -2586.238281, 168.038635, 4.101795, -14.999999, 0.000023, 0.000006, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(azmax, 2, 7231, "vgncircir2", "Clown_Pock_sign1b", 0);
	SetDynamicObjectMaterial(azmax, 1, 9903, "pier69", "pier69_sign2", 0);
	SetDynamicObjectMaterial(azmax, 0, 15040, "cuntcuts", "piratesign01_128", 0);
	azmax = CreateDynamicObject(7666, -2591.314453, 163.586395, 9.938049, 60.495598, -90.000061, -179.999649, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterialText(azmax, 0, "К И Н О Т Е А Т Р", 140, "Arial", 50, 0, 0xFFFFFFFF, 0, 1);
	azmax = CreateDynamicObject(19445, -2591.541260, 163.724228, 10.017247, 0.000000, 0.000000, 90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(azmax, 0, 10765, "airportgnd_sfse", "black64", 0);
	azmax = CreateDynamicObject(7666, -2591.864746, 163.586395, 10.738050, 60.495598, -90.000061, -179.999649, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterialText(azmax, 0, "AZ", 140, "Arial", 199, 0, 0xFFFFFFFF, 0, 1);
	azmax = CreateDynamicObject(7666, -2594.467041, 163.586395, 10.688049, 60.495598, -90.000038, -179.999741, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterialText(azmax, 0, "в„–", 140, "Webdings", 170, 0, 0xFFFFFFFF, 0, 1);
	azmax = CreateDynamicObject(1827, -2594.461182, 164.051331, 10.570064, 89.999992, 89.999992, -89.999992, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(azmax, 1, 10765, "airportgnd_sfse", "black64", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(13646, -2594.468262, 164.241425, 10.553470, 89.999992, 89.999992, -89.999992, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(azmax, 1, 10765, "airportgnd_sfse", "white", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(13646, -2596.170898, 164.251419, 10.563470, 89.999992, 90.000000, -89.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(azmax, 1, 10765, "airportgnd_sfse", "black64", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(13646, -2596.526367, 164.261414, 10.563470, 89.999992, 90.000000, -89.999969, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 2
	SetDynamicObjectMaterial(azmax, 1, 10765, "airportgnd_sfse", "white", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(983, -2596.984375, 163.104248, 4.007215, 0.000000, 0.000000, 270.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(azmax, 5, 6284, "bev_law2", "glass_fence_64hv", 0);
	SetDynamicObjectMaterial(azmax, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	azmax = CreateDynamicObject(2431, -2598.487793, 168.038635, 6.501795, -14.999999, 0.000015, 0.000004, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(azmax, 2, 6349, "sunbill_law2", "SunBillB01", 0);
	SetDynamicObjectMaterial(azmax, 1, 17535, "lae2billboards", "SunBillB03", 0);
	SetDynamicObjectMaterial(azmax, 0, 13598, "destructo", "sunshinebillboard", 0);
	azmax = CreateDynamicObject(19445, -2597.560303, 167.978043, 3.155647, 90.000000, 0.000000, 90.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 1
	SetDynamicObjectMaterial(azmax, 0, 1809, "cj_hi_fi", "CJ_speaker_6", 0);
	azmax = CreateDynamicObject(2431, -2598.487793, 168.038635, 5.301795, -14.999999, 0.000015, 0.000004, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(azmax, 2, 6336, "sunset02_law2", "SunBillB08", 0);
	SetDynamicObjectMaterial(azmax, 1, 6336, "sunset02_law2", "SunBillB07", 0);
	SetDynamicObjectMaterial(azmax, 0, 6349, "sunbill_law2", "SunBillB02", 0);
	azmax = CreateDynamicObject(2431, -2598.487793, 168.038635, 4.101795, -14.999999, 0.000015, 0.000004, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 3
	SetDynamicObjectMaterial(azmax, 2, 6354, "sunset03_law2", "SunBillB06", 0);
	SetDynamicObjectMaterial(azmax, 1, 6354, "sunset03_law2", "billLA02", 0);
	SetDynamicObjectMaterial(azmax, 0, 6354, "sunset03_law2", "billLA01", 0);
	azmax = CreateDynamicObject(983, -2600.165039, 166.264313, 4.007215, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, 300.0); // 6
	SetDynamicObjectMaterial(azmax, 5, 6284, "bev_law2", "glass_fence_64hv", 0);
	SetDynamicObjectMaterial(azmax, 4, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 3, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 2, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 1, 19962, "samproadsigns", "materialtext1", 0);
	SetDynamicObjectMaterial(azmax, 0, 19962, "samproadsigns", "materialtext1", 0);
	CreateDynamicObject(1333, -2648.600098, 166.600006, 4.100000, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
	CreateDynamicObject(1333, -2621.100098, 166.699997, 4.100000, 0.000000, 0.000000, 0.000000, -1, -1, -1, STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // 0
